### ISSUE TITLE
NetmikoTimeoutException for Dell Switch

### ISSUE THREAD

**Issue by roshanraj30** [ktbyers/nornir_netmiko#11]
I'm new to Nornir, I was trying to pull "show version" output on a Dell switch but it seems to be throwing a NetmikoTimeoutException .

```
vvvv netmiko_send_command ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.6/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 550, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.6/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.6/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 32, in netmiko_send_command
    result = net_connect.send_command(command_string, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/utilities.py", line 347, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1390, in send_command
    new_data = self.read_until_pattern(pattern=re.escape(cmd))
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 627, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 561, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

^^^^ END netmiko_send_command ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Below are the session logs, it seems to be executing fine (device_type: 'dell_os6')

```
sas19>
sas19>
sas19>enable
Password:***************

sas19#
sas19#terminal length 0

sas19#
sas19#
sas19#show version

Machine Description............... Dell Networking Switch
System Model ID................... N4032F
Machine Type...................... Dell Networking N4032F
Serial Number..................... 
Manufacturer...................... 0xbc00
Burned In MAC Address............. 
System Object ID.................. 
CPU Version....................... 
SOC Version....................... 
HW Version........................ 3
CPLD Version...................... 17

unit active      backup      current-active next-active
---- ----------- ----------- -------------- --------------
1    6.3.1.8     6.2.0.5     6.3.1.8        6.3.1.8
2    6.3.1.8     6.2.7.2     6.3.1.8        6.3.1.8


sas19#
```

Same error if I use device_type: 'cisco_ios'

```
vvvv netmiko_send_command ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.6/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 550, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.6/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.6/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 32, in netmiko_send_command
    result = net_connect.send_command(command_string, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/utilities.py", line 347, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1390, in send_command
    new_data = self.read_until_pattern(pattern=re.escape(cmd))
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 627, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 561, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.

^^^^ END netmiko_send_command ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Session Output for cisco_ios:

```
sas19>
sas19>terminal length 0
        ^
% Invalid input detected at '^' marker.

sas19>terminal width 511
        ^
% Invalid input detected at '^' marker.

sas19>
sas19>enable
Password:***************

sas19#
sas19#
sas19#show version

Machine Description............... Dell Networking Switch
System Model ID................... N4032F
Machine Type...................... Dell Networking N4032F
Serial Number..................... 
Manufacturer...................... 0xbc00
Burned In MAC Address............. 
System Object ID.................. 
CPU Version....................... 
SOC Version....................... 
HW Version........................ 3
CPLD Version...................... 17

unit active      backup      current-active next-active
---- ----------- ----------- -------------- --------------
1    6.3.1.8     6.2.0.5     6.3.1.8        6.3.1.8
2    6.3.1.8     6.2.7.2     6.3.1.8        6.3.1.8


sas19#

```

**Comment by ktbyers** [comment]
Can you show me the logging output of your Dell switch using the dell_os6 device type?

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

Is this Dell Switch in fact using Dell OS6?

**Comment by roshanraj30** [comment]
Yes it is indeed a Dell OS6 switch. Below is the logging output:

```
[rr21246@zs-netbkp01 Config]$ sudo more test.log 
DEBUG:paramiko.transport:starting thread (client mode): 0xe5abcf98
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.7.1
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_6.8
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_6.8)
DEBUG:paramiko.transport:kex algos:['curve25519-sha256@libssh.org', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group14-sha1'] server key:['ssh-rsa', 'ssh-dss'] client encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'arcf
our', 'arcfour128', 'arcfour256', 'chacha20-poly1305@openssh.com', ''] server encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'arcfour', 'arcfour128', 'arcfour256', 'chacha20-poly1305@openssh.com', ''] client mac:['hmac-sha1', 'hmac-
sha1-etm@openssh.com', 'hmac-md5-etm@openssh.com', 'umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha1-96-etm@openssh.com', 'hmac-md5-96-etm@openssh.com', 'hmac-md5', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-ri
pemd160-etm@openssh.com', 'hmac-ripemd160', 'hmac-ripemd160@openssh.com', 'hmac-sha1-96', 'hmac-md5-96', ''] server mac:['hmac-sha1', 'hmac-sha1-etm@openssh.com', 'hmac-md5-etm@openssh.com', 'umac-64-etm@openssh.com', 'umac-128-etm@open
ssh.com', 'hmac-sha1-96-etm@openssh.com', 'hmac-md5-96-etm@openssh.com', 'hmac-md5', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-ripemd160-etm@openssh.com', 'hmac-ripemd160', 'hmac-ripemd160@openssh.com', 'hmac-sha1-96', 'hmac-
md5-96', ''] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: curve25519-sha256@libssh.org
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha1
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for 10.1.10.14: b'38bfeab8fab6f9c99a25a6bc79aad25b'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:Received global request "hostkeys-00@openssh.com"
DEBUG:paramiko.transport:Rejecting "hostkeys-00@openssh.com" global request from server.
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = '\r\nsas19>'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 
sas19>
DEBUG:netmiko:repr = '\r\nsas19>'
DEBUG:netmiko:read_channel: 
sas19>
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = ''
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 
DEBUG:netmiko:repr = ''
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = ''
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 
DEBUG:netmiko:repr = ''
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = ''
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 
DEBUG:netmiko:repr = ''
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = '\r\nsas19>'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 
sas19>
DEBUG:netmiko:repr = '\r\nsas19>'
DEBUG:netmiko:read_channel: 
sas19>
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = ''
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 
DEBUG:netmiko:repr = ''
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is sas19>
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: sas19
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = '\r\nsas19>'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 
sas19>
DEBUG:netmiko:repr = '\r\nsas19>'
DEBUG:netmiko:_read_channel_expect read_data: 
sas19>
DEBUG:netmiko:Pattern found: sas19 
sas19>
DEBUG:netmiko:write_channel: b'enable\n'
DEBUG:netmiko:Pattern is: (sas19|ssword)
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = 'e'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = e
DEBUG:netmiko:repr = 'e'
DEBUG:netmiko:_read_channel_expect read_data: e
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = 'nable\r\nPassword:'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = nable
Password:
DEBUG:netmiko:repr = 'nable\r\nPassword:'
DEBUG:netmiko:_read_channel_expect read_data: nable
Password:
DEBUG:netmiko:Pattern found: (sas19|ssword) enable
Password:
DEBUG:netmiko:write_channel: b'}N9ar%fa!Tyzq(5\n'
DEBUG:netmiko:Pattern is: sas19
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = '*******'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = *******
DEBUG:netmiko:repr = '*******'
DEBUG:netmiko:_read_channel_expect read_data: *******
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = '********'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = ********
DEBUG:netmiko:repr = '********'
DEBUG:netmiko:_read_channel_expect read_data: ********
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = '\r\n\r\nsas19#'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 

sas19#
DEBUG:netmiko:repr = '\r\n\r\nsas19#'
DEBUG:netmiko:_read_channel_expect read_data: 

sas19#
DEBUG:netmiko:Pattern found: sas19 ***************

sas19#
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: sas19
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = '\r\nsas19#'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 
sas19#
DEBUG:netmiko:repr = '\r\nsas19#'
DEBUG:netmiko:_read_channel_expect read_data: 
sas19#
DEBUG:netmiko:Pattern found: sas19 
sas19#
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = ''
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 
DEBUG:netmiko:repr = ''
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:In disable_paging
DEBUG:netmiko:Command: terminal length 0

DEBUG:netmiko:write_channel: b'terminal length 0\n'
DEBUG:netmiko:Pattern is: terminal\ length\ 0
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = 'terminal '
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = terminal 
DEBUG:netmiko:repr = 'terminal '
DEBUG:netmiko:_read_channel_expect read_data: terminal 
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = 'length 0\r\n\r\nsas19#'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = length 0

sas19#
DEBUG:netmiko:repr = 'length 0\r\n\r\nsas19#'
DEBUG:netmiko:_read_channel_expect read_data: length 0

sas19#
DEBUG:netmiko:Pattern found: terminal\ length\ 0 terminal length 0

sas19#
DEBUG:netmiko:terminal length 0

sas19#
DEBUG:netmiko:Exiting disable_paging
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = ''
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 
DEBUG:netmiko:repr = ''
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: sas19
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = '\r\nsas19#'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 
sas19#
DEBUG:netmiko:repr = '\r\nsas19#'
DEBUG:netmiko:_read_channel_expect read_data: 
sas19#
DEBUG:netmiko:Pattern found: sas19 
sas19#
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = ''
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 
DEBUG:netmiko:repr = ''
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = '\r\nsas19#'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 
sas19#
DEBUG:netmiko:repr = '\r\nsas19#'
DEBUG:netmiko:read_channel: 
sas19#
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = ''
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 
DEBUG:netmiko:repr = ''
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is sas19#
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = ''
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = 
DEBUG:netmiko:repr = ''
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'sh version\n'
DEBUG:netmiko:Pattern is: sh\ version
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = 'show v'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = show v
DEBUG:netmiko:repr = 'show v'
DEBUG:netmiko:_read_channel_expect read_data: show v
DEBUG:netmiko:In strip_ansi_escape_codes
DEBUG:netmiko:repr = 'ersion\r\n\r\nMachine Description............... Dell Networking Switch\r\nSystem Model ID................... N4032F\r\nMachine Type...................... Dell Networking N4032F\r\nSerial Number....................
. \r\nManufacturer...................... 0xbc00\r\nBurned In MAC Address............. \r\nSystem Object ID.................. \r\nCPU Version....................... XLP308H-B
2\r\nSOC Version....................... \r\nHW Version........................ 3\r\nCPLD Version...................... 17\r\n\r\nunit active      backup      current-active next-active\r\n---- ----------- ----------- --------
------ --------------\r\n1    6.3.1.8     6.2.0.5     6.3.1.8        6.3.1.8\r\n2    6.3.1.8     6.2.7.2     6.3.1.8        6.3.1.8\r\n\r\n\r\nsas19#'
DEBUG:netmiko:Stripping ANSI escape codes
DEBUG:netmiko:new_output = ersion

Machine Description............... Dell Networking Switch
System Model ID................... N4032F
Machine Type...................... Dell Networking N4032F
Serial Number..................... 
Manufacturer...................... 0xbc00
Burned In MAC Address............. 
System Object ID.................. 
CPU Version....................... 
SOC Version....................... 
HW Version........................ 3
CPLD Version...................... 17

unit active      backup      current-active next-active
---- ----------- ----------- -------------- --------------
1    6.3.1.8     6.2.0.5     6.3.1.8        6.3.1.8
2    6.3.1.8     6.2.7.2     6.3.1.8        6.3.1.8


sas19#
DEBUG:netmiko:repr = 'ersion\r\n\r\nMachine Description............... Dell Networking Switch\r\nSystem Model ID................... N4032F\r\nMachine Type...................... Dell Networking N4032F\r\nSerial Number....................
. \r\nManufacturer...................... 0xbc00\r\nBurned In MAC Address............. \r\nSystem Object ID.................. \r\nCPU Version....................... XLP308H-B
2\r\nSOC Version....................... \r\nHW Version........................ 3\r\nCPLD Version...................... 17\r\n\r\nunit active      backup      current-active next-active\r\n---- ----------- ----------- --------
------ --------------\r\n1    6.3.1.8     6.2.0.5     6.3.1.8        6.3.1.8\r\n2    6.3.1.8     6.2.7.2     6.3.1.8        6.3.1.8\r\n\r\n\r\nsas19#'
DEBUG:netmiko:_read_channel_expect read_data: ersion

Machine Description............... Dell Networking Switch
System Model ID................... N4032F
Machine Type...................... Dell Networking N4032F
Serial Number..................... 
Manufacturer...................... 0xbc00
Burned In MAC Address............. 
System Object ID.................. 
CPU Version....................... 
SOC Version....................... 
HW Version........................ 3
CPLD Version...................... 17

unit active      backup      current-active next-active
---- ----------- ----------- -------------- --------------
1    6.3.1.8     6.2.0.5     6.3.1.8        6.3.1.8
2    6.3.1.8     6.2.7.2     6.3.1.8        6.3.1.8


sas19#
```

**Comment by ktbyers** [comment]
It looks like you probably need to use the canonical version of the command i.e. `show version` and not the abbreviated version of the command.

Alternatively, you could turn off `global_cmd_verify=False` (which is an argument to ConnectHandler).


Regards, Kirk

**Comment by roshanraj30** [comment]
I feel stupid now! Yes, you're right it was because of the abbreviated version. Thanks a lot for your quick support.
