### ISSUE TITLE
Netmiko Timeout

### ISSUE THREAD

**Issue by fawaleb** [ktbyers/nornir_netmiko#17]
When connecting to a device that is slow in responding I get a netmiko timeout and the following error. There needs to be a way to pass the conn_timeout variable.

---- netmiko_send_command ** changed : False ----------------------------------- ERROR
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 931, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 412, in connect
    server_key = t.get_remote_server_key()
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 834, in get_remote_server_key
    raise SSHException("No existing session")
paramiko.ssh_exception.SSHException: No existing session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.6/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "/usr/local/lib/python3.6/site-packages/nornir/core/inventory.py", line 502, in get_connection
    extras=conn.extras,
  File "/usr/local/lib/python3.6/site-packages/nornir/core/inventory.py", line 553, in open_connection
    configuration=configuration,
  File "/usr/local/lib/python3.6/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
  File "/usr/local/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 315, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/cisco/cisco_ios.py", line 17, in __init__
    return super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 346, in __init__
    self._open()
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 351, in _open
    self.establish_connection()
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 976, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.ssh_exception.NetmikoTimeoutException: Paramiko: 'No existing session' error: try increasing 'conn_timeout' to 10 seconds or larger.

^^^^ END cdp_map ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Process finished with exit code 0

**Comment by Sober092** [comment]
the issue ahead shown solution. you should appoint 'extras' parameter in yml.
there are also answers in Nornir source code :)
`
from nornir.core.inventory import Host
import json
print(json.dumps(Host.schema(), indent=4))`

https://nornir.readthedocs.io/en/latest/tutorial/inventory.html

**Comment by ktbyers** [comment]
`conn_timeout` is a supported __init__ argument. It should be available in Netmiko 3.4.0.
