### ISSUE TITLE
Unable to use nornir_netmiko with nornir 3

### ISSUE THREAD

**Issue by ledelmann** [ktbyers/nornir_netmiko#25]
Hello Kirk,

I would like to use netmiko_nornir with nornir 3.1.1, but when I try to run the script I receive the following error although the packages are installed. The python3 script is executed on Ubuntu (WSL). Could you please take a look?

Script:
```
from nornir import InitNornir
from nornir_utils.plugins.functions import print_result
import nornir_netmiko

nr = InitNornir(config_file="config.yaml")
nr.inventory.defaults.password = getpass.getpass(prompt=nr.inventory.defaults.username + "'s password: ")

def show_command(task):
    r = task.run(netmiko_send_command, command_string="show ip interface brief", use_genie=True)
    print_result(r)

nr.run(task=show_command)
```

```
~/venv$ pip3 freeze | grep "nornir\|netmiko"
netmiko==3.4.0
nornir==3.1.1
nornir-ansible==2021.7.30
nornir-jinja2==0.2.0
nornir-napalm==0.1.2
nornir-netbox==0.2.1
nornir-netmiko==0.1.2
nornir-scrapli==2021.7.30
nornir-utils==0.1.2

```
Error message:
```
$ python3 nornir_test.py
Traceback (most recent call last):
  File "nornir_test.py", line 5, in <module>
    import nornir_netmiko
  File "/home/lukas/venv/nornir_netmiko.py", line 12, in <module>
    nr = InitNornir(config_file="config.yaml")
  File "/home/lukas/venv/lib/python3.8/site-packages/nornir/init_nornir.py", line 52, in InitNornir
    ConnectionPluginRegister.auto_register()
  File "/home/lukas/venv/lib/python3.8/site-packages/nornir/core/plugins/register.py", line 20, in auto_register
    discovered_plugins: Dict[str, T] = {
  File "/home/lukas/venv/lib/python3.8/site-packages/nornir/core/plugins/register.py", line 21, in <dictcomp>
    entry_point.name: entry_point.load()
  File "/home/lukas/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/lukas/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'nornir_netmiko.connections'; 'nornir_netmiko' is not a package
```

Thanks a lot.

**Comment by ktbyers** [comment]
@ledelmann Can you show me the output from the following:

```
which python3
python3 -m pip freeze | grep nornir
```

**Comment by ledelmann** [comment]
@ktbyers Thanks for your fast reply.

```
(venv) lukas@DESKTOP-43BT1RB:~/venv$ which python3
/home/lukas/venv/bin/python3
```

```
(venv) lukas@DESKTOP-43BT1RB:~/venv$ python3 -m pip freeze | grep nornir
nornir==3.1.1
nornir-ansible==2021.7.30
nornir-jinja2==0.2.0
nornir-napalm==0.1.2
nornir-netbox==0.2.1
nornir-netmiko==0.1.2
nornir-scrapli==2021.7.30
nornir-utils==0.1.2
(venv) lukas@DESKTOP-43BT1RB:~/venv$
```

**Comment by ktbyers** [comment]
I would try uninstalling and reinstalling nornir-netmiko.

Either that or build a completely new virtual environment. It looks like an environment issue on your side, but I don't see what the issue is.

**Comment by ledelmann** [comment]
I reinstalled the virtual environment and now it's working :) Thanks a lot.
