### ISSUE TITLE
Is it possible to change ttp log_level when using the netmiko_send_command method with use_ttp=True 

### ISSUE THREAD

**Issue by rvmcinnis** [ktbyers/nornir_netmiko#26]
````
def tacacs_validator(task):
tacacs = task.run(netmiko_send_command,command_string='show tacacs', use_ttp=True, ttp_template='../../parser/ttp_parsers/dell_os6_show_tacacs.ttp')
task.host['tacacs'] = tacacs.result
````

When using the above code and for some reason netmiko can't ssh to a device TTP generates an output like the one below

```
09/29/2021 06:53:32.43 [TTP ERROR] 1819; Exception: Error reading SSH protocol banner
09/29/2021 06:53:32.49 [TTP ERROR] 1817; Traceback (most recent call last):
09/29/2021 06:53:32.51 [TTP ERROR] 1819; Exception: Error reading SSH protocol banner
09/29/2021 06:53:32.51 [TTP ERROR] 1817;   File "/usr/local/lib/python3.8/dist-packages/paramiko/transport.py", line 2211, in _check_banner
09/29/2021 06:53:32.53 [TTP ERROR] 1817; Traceback (most recent call last):
09/29/2021 06:53:32.53 [TTP ERROR] 1817;     buf = self.packetizer.readline(timeout)
09/29/2021 06:53:32.55 [TTP ERROR] 1817;   File "/usr/local/lib/python3.8/dist-packages/paramiko/transport.py", line 2211, in _check_banner
09/29/2021 06:53:32.56 [TTP ERROR] 1817;   File "/usr/local/lib/python3.8/dist-packages/paramiko/packet.py", line 380, in readline
09/29/2021 06:53:32.56 [TTP ERROR] 1817;     buf = self.packetizer.readline(timeout)
09/29/2021 06:53:32.57 [TTP ERROR] 1817;     buf += self._read_timeout(timeout)
09/29/2021 06:53:32.57 [TTP ERROR] 1817;   File "/usr/local/lib/python3.8/dist-packages/paramiko/packet.py", line 380, in readline
09/29/2021 06:53:32.58 [TTP ERROR] 1817;   File "/usr/local/lib/python3.8/dist-packages/paramiko/packet.py", line 609, in _read_timeout
09/29/2021 06:53:32.58 [TTP ERROR] 1817;     buf += self._read_timeout(timeout)
09/29/2021 06:53:32.58 [TTP ERROR] 1817;     raise EOFError()
09/29/2021 06:53:32.58 [TTP ERROR] 1817;   File "/usr/local/lib/python3.8/dist-packages/paramiko/packet.py", line 609, in _read_timeout
09/29/2021 06:53:32.58 [TTP ERROR] 1819; Exception: Error reading SSH protocol banner
09/29/2021 06:53:32.58 [TTP ERROR] 1817; EOFError
09/29/2021 06:53:32.59 [TTP ERROR] 1817;     raise EOFError()
09/29/2021 06:53:32.60 [TTP ERROR] 1817; Traceback (most recent call last):
09/29/2021 06:53:32.60 [TTP ERROR] 1817; 
09/29/2021 06:53:32.61 [TTP ERROR] 1817; EOFError
09/29/2021 06:53:32.62 [TTP ERROR] 1817;   File "/usr/local/lib/python3.8/dist-packages/paramiko/transport.py", line 2211, in _check_banner
09/29/2021 06:53:32.63 [TTP ERROR] 1817; During handling of the above exception, another exception occurred:
09/29/2021 06:53:32.65 [TTP ERROR] 1817; 
09/29/2021 06:53:32.67 [TTP ERROR] 1817;     buf = self.packetizer.readline(timeout)
09/29/2021 06:53:32.67 [TTP ERROR] 1817; 
09/29/2021 06:53:32.68 [TTP ERROR] 1817; During handling of the above exception, another exception occurred:
09/29/2021 06:53:32.68 [TTP ERROR] 1817;   File "/usr/local/lib/python3.8/dist-packages/paramiko/packet.py", line 380, in readline
09/29/2021 06:53:32.68 [TTP ERROR] 1817; Traceback (most recent call last):
09/29/2021 06:53:32.68 [TTP ERROR] 1817; 
09/29/2021 06:53:32.69 [TTP ERROR] 1817;     buf += self._read_timeout(timeout)
09/29/2021 06:53:32.69 [TTP ERROR] 1817;   File "/usr/local/lib/python3.8/dist-packages/paramiko/transport.py", line 2039, in run
09/29/2021 06:53:32.69 [TTP ERROR] 1817; Traceback (most recent call last):
09/29/2021 06:53:32.69 [TTP ERROR] 1817;   File "/usr/local/lib/python3.8/dist-packages/paramiko/transport.py", line 2039, in run
09/29/2021 06:53:32.69 [TTP ERROR] 1817;     self._check_banner()
09/29/2021 06:53:32.69 [TTP ERROR] 1817;   File "/usr/local/lib/python3.8/dist-packages/paramiko/packet.py", line 609, in _read_timeout
09/29/2021 06:53:32.69 [TTP ERROR] 1817;     self._check_banner()
09/29/2021 06:53:32.70 [TTP ERROR] 1817;   File "/usr/local/lib/python3.8/dist-packages/paramiko/transport.py", line 2215, in _check_banner
09/29/2021 06:53:32.70 [TTP ERROR] 1817;     raise EOFError()
09/29/2021 06:53:32.70 [TTP ERROR] 1817;   File "/usr/local/lib/python3.8/dist-packages/paramiko/transport.py", line 2215, in _check_banner
09/29/2021 06:53:32.70 [TTP ERROR] 1817;     raise SSHException(
09/29/2021 06:53:32.70 [TTP ERROR] 1817; EOFError
09/29/2021 06:53:32.70 [TTP ERROR] 1817;     raise SSHException(
09/29/2021 06:53:32.70 [TTP ERROR] 1817; paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
09/29/2021 06:53:32.70 [TTP ERROR] 1817; 
09/29/2021 06:53:32.70 [TTP ERROR] 1817; paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
```

 
I know that you can change that when you are using TTP by changing the log_level argument to 'CRITICAL'
(https://ttp.readthedocs.io/en/latest/API%20reference.html)

log_level (str) level of logging “DEBUG”, “INFO”, “WARNING”, “ERROR”, “CRITICAL”

Is it possible to do something like that or I will have to store the output from the netmiko_send_command task and then parse it on a separate task?

thanks for your help!

**Comment by ktbyers** [comment]
For `use_ttp=True`, Netmiko does not support the additional logging arguments so you would have to grab the raw output and re-parse it yourself. You could probably just copy modify the code that is in Netmiko's utilities.py module.

You could also look at the `run_ttp_template` function which is also in utilities.py. That does support any generic arguments to `ttp` (i.e. it supports **kwargs).

**Comment by rvmcinnis** [comment]
thanks Kirk, just wanted to make sure. I really appreciate it
