### ISSUE TITLE
OSError: Search pattern never detected in send_command Cisco IOS

### ISSUE THREAD

**Issue by veytsberg** [ktbyers/nornir_netmiko#27]
Hello, saving configuration cisco_ios does not work in nornir-netmiko 0.1.2, but it works fine in nornir 2.4.0

Name: nornir
Version: 3.2.0

Name: nornir-netmiko
Version: 0.1.2

cmd = 'wr'
r = nr.run(
    task=netmiko_send_command,
    command_string=cmd)
print_result(r)

or

r = nr.run(
    task=netmiko_save_config)
print_result(r)

netmiko_send_command************************************************************
* FL3-R2-SW02** changed : False ***************************************
vvvv netmiko_send_command ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
Traceback (most recent call last):
  File "\.virtualenvs\nornir_template-master\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "\.virtualenvs\nornir_template-master\lib\site-packages\nornir_netmiko\tasks\netmiko_send_command.py", line 32, in netmiko_send_command
    result = net_connect.send_command(command_string, **kwargs)
  File "\.virtualenvs\nornir_template-master\lib\site-packages\netmiko\utilities.py", line 500, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "\.virtualenvs\nornir_template-master\lib\site-packages\netmiko\base_connection.py", line 1535, in send_command
    raise IOError(
OSError: Search pattern never detected in send_command: FL3\-R2\-SW02\#

^^^^ END netmiko_send_command ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by ktbyers** [comment]
@veytsberg Netmiko is saying the prompt `FL3-R2-SW02#` never came back after executing `wr`?

Is the device prompting for anything after executing `wr` (for example, after an OS upgrade where it prompts you that you want to do this save configuration).
