### ISSUE TITLE
Installation error: No module named 'six'

### ISSUE THREAD

**Issue by ShadowSZ72** [ktbyers/nornir_netmiko#38]
I'm trying to install module and I get this error

```
pip install nornir-netmiko==0.1.2
Collecting nornir-netmiko==0.1.2
  Using cached nornir_netmiko-0.1.2-py3-none-any.whl (10 kB)
Collecting netmiko<4.0.0,>=3.4.0
  Using cached netmiko-3.4.0-py3-none-any.whl (178 kB)
Requirement already satisfied: setuptools>=38.4.0 in ./testvenv2/lib/python3.8/site-packages (from netmiko<4.0.0,>=3.4.0->nornir-netmiko==0.1.2) (44.0.0)
Collecting tenacity
  Using cached tenacity-8.0.1-py3-none-any.whl (24 kB)
Collecting ntc-templates
  Using cached ntc_templates-3.0.0-py3-none-any.whl (303 kB)
Collecting pyserial
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Collecting scp>=0.13.2
  Using cached scp-0.14.4-py2.py3-none-any.whl (8.6 kB)
Collecting paramiko>=2.6.0
  Using cached paramiko-2.11.0-py2.py3-none-any.whl (212 kB)
Collecting textfsm<2.0.0,>=1.1.0
  Using cached textfsm-1.1.3.tar.gz (55 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/kolov_aa/reps/nocportal/testvenv2/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-se22t2kg/textfsm/setup.py'"'"'; __file__='"'"'/tmp/pip-install-se22t2kg/textfsm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-se22t2kg/textfsm/pip-egg-info
         cwd: /tmp/pip-install-se22t2kg/textfsm/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-se22t2kg/textfsm/setup.py", line 20, in <module>
        import textfsm
      File "/tmp/pip-install-se22t2kg/textfsm/textfsm/__init__.py", line 11, in <module>
        from textfsm.parser import *
      File "/tmp/pip-install-se22t2kg/textfsm/textfsm/parser.py", line 41, in <module>
        import six
    ModuleNotFoundError: No module named 'six'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by sydasif** [comment]
pip install six
pip install nornir-netmiko 

will solve your issue, hopefully.

**Comment by ktbyers** [comment]
Or downgrade to `textfsm==1.1.2` (textfsm broke their library when they released textfsm 1.1.3)
