### ISSUE TITLE
cmd_verfiy=False still verifying command in Juniper

### ISSUE THREAD

**Issue by nanisyako** [ktbyers/nornir_netmiko#48]
env:

netmiko==4.1.1
nornir-netmiko==0.2.0

task:

```
cmd_mapper = {
            "arista-eos": [
                f"show tech-support >>flash:{task.host}_techsupport_{_time}.tar",
                f"bash sudo tar -czvf - /var/log/qt/ > /mnt/flash/qt-logs-{task.host}_{_time}.tar.gz",
            ],
            "junos": [
                f"request support information | save /var/tmp/{task.host}_RSI_{_time}.txt"
            ],
        }
        cmd_list = cmd_mapper[
            f"{task.host.platform}"
        ]  # mapping commands for each vendor
        file_name = file_mapper[f"{task.host.platform}"]

        for cmd in cmd_list:
            print(cmd)
            results = task.run(
                task=netmiko_send_command,
                command_string=cmd,
                cmd_verify=False,
                read_timeout=1500,
            )
 ```
error:

before the timeout:
```
netmiko_send_command -> failed: [test-1-2-sanjose]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.8/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 32, in netmiko_send_command
    result = net_connect.send_command(command_string, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/netmiko/utilities.py", line 596, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1691, in send_command
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout:
Pattern not detected: 'user@test\-1\\-2\\-sanjose>' in output.

Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.
```

**Comment by ktbyers** [comment]
Doesn't look like a cmd_verify issue. Have you looked at the `session_log` to see what is going on?

**Comment by ktbyers** [comment]
Can you show me what the `session_log` looks like for that failing command?

**Comment by nanisyako** [comment]
so the device actually has finished writing the requested rsi to /var/tmp but somehow netmiko is still trying to read_channel probably  the debug.log shows:
```
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
```
while the task has failed with:
```
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1691, in send_command
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout:
Pattern not detected: 'user@switch\\c1\\-site1>' in output.

Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.
```
here is how I collect the logs,please let me know if that would not catch it:
```
logging.basicConfig(filename="netmiko_global.log", level=logging.DEBUG)
logger = logging.getLogger("netmiko")
```
Also, is there a way of forcing nornir-netmiko to try the next task which is file_transfer in my case, and then fail?

**Comment by ktbyers** [comment]
I am going to close this as it isn't being actively worked on...if you still want to work on this, let me know and we can re-open it.
