### ISSUE TITLE
Problem with parallelisation for different hosts

### ISSUE THREAD

**Issue by akarneliuk** [ktbyers/nornir_netmiko#6]
Hey Kirk,

first of all, thanks for a nice tool for the network engineers. I have, hopefully, a quick question. Here is the sample code I have:
```python
#!/usr/bin/env python

# Modules
from nornir import InitNornir
from nornir.core.task import Result, Task
from nornir_netmiko import netmiko_send_command, netmiko_send_config
import os
import logging

# Variables
backup_folder = 'config_backups'

# Tasks
def save_config(task: Task, bfd: str) -> Result:
    """
    This task is used to backup the configuration from the network element to a local hosts
    """
    if task.host.platform == 'eos':
        cmd2 = "show run"
        priveleged_mode = True

    elif task.host.platform == 'cisco_xr':
        cmd2 = "show run"
        priveleged_mode = False

    elif task.host.platform == 'nokia_sros':
        cmd2 = "admin display"
        priveleged_mode = False

    r2 = nr.run(task=netmiko_send_command, command_string=cmd2, enable=priveleged_mode)

    if task.host.name in nr.data.failed_hosts:
        task.host['task_2'] = False
    
    else:
        with open(f'{bfd}/{task.host.name}.txt', 'w') as f:
            f.write(r2[task.host.name][0].result)

        task.host['task_2'] = True

    return Result(host=task.host, result=task.host['task_2'])

# Body
if __name__ == "__main__":
    nr = InitNornir(config_file='config.yaml')

    test_2_results = nr.run(task=save_config, bfd=backup_folder)
```

It does nothing but saves the configuration.
I have 3 devices from a different vendors as you could see from the code. The issue I face is that I'm trying to back up the configuration from them in a single run. 

If I run the script for one device (doesn't matter Nokia, Cisco or Arista), the script works properly is stored properly. 
```
2020-10-10 17:24:40,133 -  nornir.core -     INFO -        run() - Running task 'save_config' with args {'bfd': 'config_backups'} on 1 hosts
2020-10-10 17:24:40,134 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show run', 'enable': False} on 1 hosts
```

However, if I try to do that simultaneously for multiple devices (1x Arista and 1xCisco), I'm getting errors something like:

```
2020-10-10 17:23:39,923 -  nornir.core -     INFO -        run() - Running task 'save_config' with args {'bfd': 'config_backups'} on 3 hosts
2020-10-10 17:23:39,924 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show run', 'enable': True} on 3 hosts
2020-10-10 17:23:39,924 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show run', 'enable': False} on 3 hosts
2020-10-10 17:23:39,925 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'admin display', 'enable': False} on 3 hosts
2020-10-10 17:23:40,032 - nornir.core.task -    ERROR -      start() - Host 'XR1': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/Users/anton.karneliuk/Documents/D/Dev/nornir-network-functional/venv/lib/python3.7/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/Users/anton.karneliuk/Documents/D/Dev/nornir-network-functional/venv/lib/python3.7/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/Users/anton.karneliuk/Documents/D/Dev/nornir-network-functional/venv/lib/python3.7/site-packages/paramiko/packet.py", line 607, in _read_timeout
    x = self.__socket.recv(128)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anton.karneliuk/Documents/D/Dev/nornir-network-functional/venv/lib/python3.7/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/Users/anton.karneliuk/Documents/D/Dev/nornir-network-functional/venv/lib/python3.7/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "/Users/anton.karneliuk/Documents/D/Dev/nornir-network-functional/venv/lib/python3.7/site-packages/nornir/core/inventory.py", line 448, in get_connection
    extras=conn.extras,
  File "/Users/anton.karneliuk/Documents/D/Dev/nornir-network-functional/venv/lib/python3.7/site-packages/nornir/core/inventory.py", line 499, in open_connection
    configuration=configuration,
  File "/Users/anton.karneliuk/Documents/D/Dev/nornir-network-functional/venv/lib/python3.7/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
  File "/Users/anton.karneliuk/Documents/D/Dev/nornir-network-functional/venv/lib/python3.7/site-packages/netmiko/ssh_dispatcher.py", line 312, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/Users/anton.karneliuk/Documents/D/Dev/nornir-network-functional/venv/lib/python3.7/site-packages/netmiko/cisco/cisco_xr.py", line 10, in __init__
    return super().__init__(*args, **kwargs)
  File "/Users/anton.karneliuk/Documents/D/Dev/nornir-network-functional/venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 346, in __init__
    self._open()
  File "/Users/anton.karneliuk/Documents/D/Dev/nornir-network-functional/venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 351, in _open
    self.establish_connection()
  File "/Users/anton.karneliuk/Documents/D/Dev/nornir-network-functional/venv/lib/python3.7/site-packages/netmiko/cisco/cisco_xr.py", line 14, in establish_connection
    super().establish_connection(width=511, height=511)
  File "/Users/anton.karneliuk/Documents/D/Dev/nornir-network-functional/venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 920, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/Users/anton.karneliuk/Documents/D/Dev/nornir-network-functional/venv/lib/python3.7/site-packages/paramiko/client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "/Users/anton.karneliuk/Documents/D/Dev/nornir-network-functional/venv/lib/python3.7/site-packages/paramiko/transport.py", line 660, in start_client
    raise e
  File "/Users/anton.karneliuk/Documents/D/Dev/nornir-network-functional/venv/lib/python3.7/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/Users/anton.karneliuk/Documents/D/Dev/nornir-network-functional/venv/lib/python3.7/site-packages/paramiko/transport.py", line 2216, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[Errno 54] Connection reset by peer
```

or

```
2020-10-10 17:09:16,179 - nornir.core.task -    ERROR -      start() - Host 'SR1': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/aaa/cases/leela/nornir-network-functional/vev/lib/python3.7/site-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/home/aaa/cases/leela/nornir-network-functional/vev/lib/python3.7/site-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aaa/cases/leela/nornir-network-functional/vev/lib/python3.7/site-packages/netmiko/base_connection.py", line 569, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/home/aaa/cases/leela/nornir-network-functional/vev/lib/python3.7/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aaa/cases/leela/nornir-network-functional/vev/lib/python3.7/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/aaa/cases/leela/nornir-network-functional/vev/lib/python3.7/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 28, in netmiko_send_command
    net_connect.enable()
  File "/home/aaa/cases/leela/nornir-network-functional/vev/lib/python3.7/site-packages/netmiko/nokia/nokia_sros_ssh.py", line 87, in enable
    return super().enable(cmd=cmd, pattern=pattern, re_flags=re_flags)
  File "/home/aaa/cases/leela/nornir-network-functional/vev/lib/python3.7/site-packages/netmiko/base_connection.py", line 1663, in enable
    if not self.check_enable_mode():
  File "/home/aaa/cases/leela/nornir-network-functional/vev/lib/python3.7/site-packages/netmiko/nokia/nokia_sros_ssh.py", line 95, in check_enable_mode
    output = self.read_until_prompt_or_pattern(pattern="ssword")
  File "/home/aaa/cases/leela/nornir-network-functional/vev/lib/python3.7/site-packages/netmiko/base_connection.py", line 664, in read_until_prompt_or_pattern
    return self._read_channel_expect(combined_pattern, re_flags=re_flags)
  File "/home/aaa/cases/leela/nornir-network-functional/vev/lib/python3.7/site-packages/netmiko/base_connection.py", line 580, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.
```

Not sure if that is a desired behaviour for a multivendor task. Any help is much appreciated.

Thanks,
Anton

**Comment by ktbyers** [comment]
Are these virtual devices or real devices?

You probably need to set the banner_timeout on your Netmiko connection arguments.


Regards,

Kirk
