### ISSUE TITLE
PaloAlto pattern not detected issue for few devices

### ISSUE THREAD

**Issue by roshanraj30** [ktbyers/nornir_netmiko#67]
We recently upgraded our pip packages to nornir: 3.4.1, nornir-netmiko: 1.0.0 & netmiko: 4.3.0

We have ~80 Palo Alto firewalls, and we are trying to SCP to a file in PaloAlto to our backup server. Below is the task:

```
def PaloAltoBackupTask(task):
    transfer = task.run(task=netmiko_send_command,
                        command_string=f'scp export configuration remote-port 22 to myusername@10.1.2.3:{fwdir}/{task.host.name}_{task.host.hostname}_{datetime.datetime.now().strftime("%Y-%m-%d_%H:%M:%S")}.xml from .merged-running-config.xml', name='GetConfigFile', use_timing=True)
    if 'yes/no' in transfer[0].result:
        confirm = task.run(task=netmiko_send_command, command_string='yes',
                           name='ConfirmConnection', use_timing=True)
        if 'password' in confirm[0].result:
            task.run(task=netmiko_send_command, command_string='supersecretpassword',
                     name='SendPasswordwC', use_timing=True)
    elif 'password' in transfer[0].result:
        task.run(task=netmiko_send_command, command_string='supersecretpassword',
                 name='SendPasswordwoC', use_timing=True)
```

I'm aware there is an SCP file_transfer function inbuilt but I think it doesn't support Palo Alto so we are using above code.

Here is the **groups.yaml**:

```
paloalto:
  platform: paloalto
  connection_options:
    netmiko:
      extras:
        device_type: "paloalto_panos"
        global_delay_factor: 4
        fast_cli: False
```

The script works fine for 95% of the devices, but consistently fails for 5% of the devices, it fails for the very first task "GetConfigFile". Here is the **traceback** that I get:

```
ReadTimeout("

Pattern not detected: '[>#]' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.

")
```

These 5% devices have very slow loading time (especially the authentication). So I tried to increase the read_timeout value for the first send_command like this but still facing the same error:

```
transfer = task.run(task=netmiko_send_command,
                        command_string=f'scp export configuration remote-port 22 to myusername@10.1.2.3:{fwdir}/{task.host.name}_{task.host.hostname}_{datetime.datetime.now().strftime("%Y-%m-%d_%H:%M:%S")}.xml from .merged-running-config.xml', name='GetConfigFile', use_timing=True, **read_timeout=180**)
```

I also noticed that the traceback was received before 180 seconds itself, so it didn't wait for the entire 180 seconds; it gave the same error within 25-30 seconds.

I've also tried below changes but still get the same error:

**banner_timeout:**
```
transfer = task.run(task=netmiko_send_command,
                        command_string=f'scp export configuration remote-port 22 to myusername@10.1.2.3:{fwdir}/{task.host.name}_{task.host.hostname}_{datetime.datetime.now().strftime("%Y-%m-%d_%H:%M:%S")}.xml from .merged-running-config.xml', name='GetConfigFile', use_timing=True, **banner_timeout=45**)
```

**conn_timeout:**
```
transfer = task.run(task=netmiko_send_command,
                        command_string=f'scp export configuration remote-port 22 to myusername@10.1.2.3:{fwdir}/{task.host.name}_{task.host.hostname}_{datetime.datetime.now().strftime("%Y-%m-%d_%H:%M:%S")}.xml from .merged-running-config.xml', name='GetConfigFile', use_timing=True, **conn_timeout=45**)
```

**auth_timeout:**
```
transfer = task.run(task=netmiko_send_command,
                        command_string=f'scp export configuration remote-port 22 to myusername@10.1.2.3:{fwdir}/{task.host.name}_{task.host.hostname}_{datetime.datetime.now().strftime("%Y-%m-%d_%H:%M:%S")}.xml from .merged-running-config.xml', name='GetConfigFile', use_timing=True, **auth_timeout=45**)
```

This script used to work fine on the older version of nornir-netmiko, although I'm not sure which version we used back then (same script is being used from last 2-3 years). We are facing this issue only after upgrading the pip packages.

**Comment by ktbyers** [comment]
You need to include the entire Python exception stack trace for at least one of the failing devices.

**Comment by roshanraj30** [comment]
> You need to include the entire Python exception stack trace for at least one of the failing devices.

Apologies, here's the entire debug for one of the failing device:

```
2023-12-08 03:49:33,003 - nornir.core.task -    ERROR -      start() - Host 'test-paloalto01': task 'GetConfigFile' failed with traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.8/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "/usr/local/lib/python3.8/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/usr/local/lib/python3.8/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/usr/local/lib/python3.8/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
  File "/usr/local/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 399, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 488, in __init__
    self._open()
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 494, in _open
    self._try_session_preparation()
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 988, in _try_session_preparation
    self.session_preparation()
  File "/usr/local/lib/python3.8/site-packages/netmiko/paloalto/paloalto_panos.py", line 68, in session_preparation
    self._test_channel_read(pattern=r"[>#]")
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1235, in _test_channel_read
    return self.read_until_pattern(pattern=pattern, read_timeout=20)
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 746, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: '[>#]' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.



2023-12-08 03:49:33,003 - nornir.core.task -    ERROR -      start() - Host 'test-paloalto01': task 'PaloAltoBackupTask' failed with traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "<stdin>", line 2, in PaloAltoBackupTask
  File "/usr/local/lib/python3.8/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: GetConfigFile (failed)
```

**Comment by ktbyers** [comment]
The error shown above is failing on the read after connecting (so right after the SSH connects, Netmiko tries to read the initial prompt).

It looks like it is failing here:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L1235

Basically Netmiko gives it 20 seconds for the initial prompt to be displayed.

Do you know why these devices are so slow? Is your AAA system overloaded or some other issue?

I think you could try to set this:

```
read_timeout_override
``` 

In your connection_options > netmiko > extras.

This should override any/all read_timeouts that get set (and use the value you set here instead).

Let me know if that works.

**Comment by roshanraj30** [comment]
> Do you know why these devices are so slow? Is your AAA system overloaded or some other issue?

The login for these devices are via local authentication (no AAA), although they have high management plane CPU utilization.

**read_timeout_override** fixed the issue for all of them, now there is only one device failing with below trace:

```
2023-12-08 21:00:03,987 - nornir.core.task -    ERROR -      start() - Host 'anothertest-pa02': task 'GetConfigFile' failed with traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1137, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/local/lib/python3.8/site-packages/paramiko/client.py", line 457, in connect
    server_key = t.get_remote_server_key()
  File "/usr/local/lib/python3.8/site-packages/paramiko/transport.py", line 902, in get_remote_server_key
    raise SSHException("No existing session")
paramiko.ssh_exception.SSHException: No existing session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.8/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
  File "/usr/local/lib/python3.8/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/usr/local/lib/python3.8/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/usr/local/lib/python3.8/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
  File "/usr/local/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 399, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 488, in __init__
    self._open()
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 493, in _open
    self.establish_connection()
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1182, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.exceptions.NetmikoTimeoutException: Paramiko: 'No existing session' error: try increasing 'conn_timeout' to 15 seconds or larger.

2023-12-08 21:00:03,988 - nornir.core.task -    ERROR -      start() - Host 'anothertest-pa02': task 'PaloAltoBackupTask' failed with traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "<stdin>", line 2, in PaloAltoBackupTask
  File "/usr/local/lib/python3.8/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: GetConfigFile (failed)
```
